foss_library/books/models.py
from foss_library.database import CRUDMixin, db

from foss_library.exceptions import OutOfStockError, OutstandingDuesError
from foss_library.transactions.models import Transaction


class Book(db.Model, CRUDMixin):
    """The Book model"""

    __tablename__ = "books"
    id = db.Column(db.Integer, primary_key=True)
    isbn = db.Column(db.String(10), unique=True, nullable=False, index=True)
    isbn13 = db.Column(db.String(13), unique=True, nullable=False, index=True)
    # the longest book title is over 26000 characters! won't use VARCHAR(X) here
    title = db.Column(db.Text)
    authors = db.Column(db.Text)
    average_rating = db.Column(db.Float)
    # langauge code is usually 3 chars long, but there is a special code qaa-qtz
    language_code = db.Column(db.String(7), index=True)
    num_pages = db.Column(db.Integer)
    ratings_count = db.Column(db.Integer)
    text_reviews_count = db.Column(db.Integer)
    publication_date = db.Column(db.DateTime)
    publisher_name = db.Column(db.String(255))
    total_stock = db.Column(db.Integer, default=1)
    # default rent per day to 1 Rs per day
    rent_per_day = db.Column(db.Integer, default=1)

    # timestamps
    created_at = db.Column(db.DateTime, default=db.func.now())
    updated_at = db.Column(db.DateTime, default=db.func.now(), onupdate=db.func.now())

    title_text_pattern_idx = db.Index(
        f"idx_{__tablename__}_title_lower_text_pattern",
        db.func.lower(title).label("lowercase_title"),
        postgresql_ops={"lowercase_title": "text_pattern_ops"},
    )
    authors_text_pattern_idx = db.Index(
        f"idx_{__tablename__}_authors_lower_text_pattern",
        db.func.lower(title).label("lowercase_authors"),
        postgresql_ops={"lowercase_authors": "text_pattern_ops"},
    )
    publisher_name_varchar_pattern_idx = db.Index(
        f"idx_{__tablename__}_publisher_lower_text_pattern",
        db.func.lower(title).label("lowercase_publisher_name"),
        postgresql_ops={"lowercase_publisher_name": "varchar_pattern_ops"},
    )

    @property
    def unreturned_stock(self):
        """Number of unreturned books"""
        unreturned_books = Transaction.query.filter_by(
            book_id=self.id, returned_at=None
        ).count()
        return unreturned_books

    @property
    def available_stock(self):
        """Returns the available stock for a Book"""
        return self.total_stock - self.unreturned_stock

    def issue_to(self, member):
        """Tries to issue a book to a member"""
        if self.available_stock < 1:
            message = f"The book '{self.title}' is out of stock"
            raise OutOfStockError(message)

        if member.can_borrow_new_book:
            txn = Transaction.create(book=self, member=member)
            return txn
        else:
            raise OutstandingDuesError()

foss_library/books/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, DecimalField, IntegerField, SelectField, StringField
from wtforms.fields.html5 import DateField, SearchField
from wtforms.validators import InputRequired, Length, NumberRange, Optional

from foss_library.utils import UniqueCheck
from .models import Book


class BookForm(FlaskForm):
    _model = Book

    title = StringField("Title", validators=[InputRequired()])
    authors = StringField("Authors", validators=[InputRequired()])
    language_code = StringField(validators=[Optional(), Length(max=7)])
    num_pages = IntegerField(validators=[InputRequired(), NumberRange(min=0)])
    publication_date = DateField(validators=[InputRequired()])
    publisher_name = StringField(validators=[InputRequired()])
    average_rating = DecimalField(validators=[Optional(), NumberRange(min=0, max=5)])
    ratings_count = IntegerField(validators=[Optional(), NumberRange(min=0)])
    text_reviews_count = IntegerField(validators=[Optional(), NumberRange(min=0)])
    total_stock = IntegerField(
        default=1, validators=[InputRequired(), NumberRange(min=0)]
    )
    rent_per_day = IntegerField(default=1, validators=[Optional(), NumberRange(min=0)])


class CreateBookForm(BookForm):
    isbn = StringField(
        "ISBN 10", validators=[InputRequired(), Length(min=10, max=10), UniqueCheck()]
    )
    isbn13 = StringField(
        "ISBN 13", validators=[InputRequired(), Length(min=13, max=13), UniqueCheck()]
    )


class UpdateBookForm(BookForm):
    isbn = StringField("ISBN 10", validators=[InputRequired(), Length(min=10, max=10)])
    isbn13 = StringField(
        "ISBN 13", validators=[InputRequired(), Length(min=13, max=13)]
    )


class SearchBookForm(FlaskForm):
    title = SearchField()
    author = SearchField()


class IssueBookForm(FlaskForm):
    member_id = SelectField("Member name", coerce=int, validate_choice=False)


class InitiateBookReturnForm(FlaskForm):
    member_id = IntegerField(validators=[InputRequired()])

foss_library/books/__init__.py
from . import models, views

foss_library/books/views.py
from math import ceil

from flask import Blueprint, flash, redirect, render_template, request, url_for
from sqlalchemy import desc

from foss_library.database import db
from foss_library.exceptions import FOSSLibraryBaseException
from foss_library.utils import flash_form_errors
from foss_library.members.models import Member
from foss_library.transactions.models import Transaction
from .forms import (
    InitiateBookReturnForm,
    IssueBookForm,
    CreateBookForm,
    SearchBookForm,
    UpdateBookForm,
)
from .models import Book

blueprint = Blueprint("books", __name__, url_prefix="/books", static_folder="../static")


def filter_books_by_request_args():
    title = request.args.get("title")
    author = request.args.get("author")

    filters = []

    if title:
        title = title.lower()
        filters.append(db.func.lower(Book.title).like(f"%{(title)}%"))

    if author:
        author = author.lower()
        filters.append(db.func.lower(Book.authors).like(f"%{author}%"))

    return Book.query.filter(*filters)


@blueprint.route("/", methods=("GET",))
def list_books():
    """List books"""
    books_on_each_page = 20

    # get page from request args, e.g. /books?page=1
    page = request.args.get("page", 1)
    page = int(page)

    # set limit and offset for SQL query
    limit = books_on_each_page
    offset = (page - 1) * books_on_each_page

    books_query = filter_books_by_request_args()
    books = books_query.limit(limit).offset(offset).all()

    total_pages = ceil(books_query.count() / books_on_each_page)

    if page > 1 and page > total_pages:
        flash(f"Page {page} is out of range", "warning")

    search_form = SearchBookForm(request.args)

    return render_template(
        "books/list_books.html",
        books=books,
        current_page=page,
        total_pages=total_pages,
        search_form=search_form,
    )


@blueprint.route("/create", methods=("GET", "POST"))
def create_book():
    """Create a new book"""
    form = CreateBookForm()
    if form.validate_on_submit():
        book = Book()
        form.populate_obj(book)
        book.save()
        flash("Book created successfully!", "success")
        return redirect(url_for("books.list_books"))

    search_form = SearchBookForm(request.args)

    flash_form_errors(form)
    if form.errors:
        status_code = 400
    else:
        status_code = 200

    return (
        render_template("books/create_book.html", form=form, search_form=search_form),
        status_code,
    )


@blueprint.route("/update/<int:id>", methods=("GET", "POST"))
def update_book(id):
    """Update an existing book"""
    book = Book.query.get(id)
    if book is None:
        return render_template("404.html"), 404

    form = UpdateBookForm(obj=book)
    if form.validate_on_submit():
        form.populate_obj(book)
        book.save()
        flash("Book updated successfully!", "success")
        return redirect(url_for("books.list_books"))

    search_form = SearchBookForm(request.args)

    flash_form_errors(form)
    if form.errors:
        status_code = 400
    else:
        status_code = 200

    return (
        render_template(
            "books/update_book.html", book=book, form=form, search_form=search_form
        ),
        status_code,
    )


@blueprint.route("/delete/<int:id>", methods=("POST",))
def delete_book(id):
    """Delete a book"""
    book = Book.query.get(id)
    if book is None:
        return render_template("404.html"), 404

    book.delete()
    flash("Book deleted successfully!", "success")
    return redirect(url_for("books.list_books"))


@blueprint.route("/show/<int:id>", methods=("GET",))
def show_book(id):
    """Show a book"""
    book = Book.query.get_or_404(id)

    issue_form = IssueBookForm(obj=book)
    return_form = InitiateBookReturnForm(obj=book)
    search_form = SearchBookForm(request.args)

    members = Member.query.all()
    issue_form.member_id.choices = [(m.id, m.name) for m in members]

    return render_template(
        "books/show_book.html",
        book=book,
        issue_form=issue_form,
        return_form=return_form,
        search_form=search_form,
    )


@blueprint.route("/issue/<int:id>", methods=("POST",))
def issue_book(id):
    """Issue a book"""
    book = Book.query.get_or_404(id)

    form = IssueBookForm(obj=book)
    if form.validate_on_submit():
        member_id = form.member_id.data
        member = Member.query.get(member_id)
        if member is None:
            flash(
                f"Member with ID {member_id} doesn't exist. Please check your input",
                "warning",
            )
            return redirect(url_for("books.show_book", id=id))

        try:
            book.issue_to(member)
        except FOSSLibraryBaseException as e:
            flash(str(e), "danger")
            return redirect(url_for("books.show_book", id=id))

        flash("Book has been issued", "success")
        return redirect(url_for("books.show_book", id=id))

    flash_form_errors(form)
    return redirect(url_for("books.show_book", id=id))


@blueprint.route("/initiate_return/<int:id>", methods=("POST",))
def initiate_book_return(id):
    """Initiate a book return"""
    book = Book.query.get_or_404(id)

    form = InitiateBookReturnForm(obj=book)
    if form.validate_on_submit():
        member_id = form.member_id.data
        member = Member.query.get(member_id)
        if member is None:
            flash(
                f"Member with ID {member_id} doesn't exist. Please check your input",
                "warning",
            )
            return redirect(url_for("books.show_book", id=id)), 400

        txn = Transaction.query.filter_by(
            member=member, book=book, returned_at=None
        ).first()
        if txn is None:
            flash(f"Member with ID {member_id} hasn't borrowed this book.")
            return redirect(url_for("books.show_book", id=id)), 400

        return redirect(url_for("transactions.show_transaction", id=txn.id)), 400

    else:
        flash_form_errors(form)
        if form.errors:
            status_code = 400
        else:
            status_code = 200

        return redirect(url_for("books.show_book", id=id)), status_code

foss_library/transactions/views.py
from math import ceil

from flask import Blueprint, flash, redirect, render_template, request, url_for
from sqlalchemy import desc

from .models import Transaction

blueprint = Blueprint(
    "transactions", __name__, url_prefix="/transactions", static_folder="../static"
)


@blueprint.route("/", methods=("GET",))
def list_transactions():
    transactions_on_each_page = 20

    page = request.args.get("page", 1)
    page = int(page)

    total_pages = ceil(Transaction.query.count() / transactions_on_each_page)
    if page > 1 and page > total_pages:
        flash(f"Page {page} is out of range", "warning")

    limit = transactions_on_each_page
    offset = (page - 1) * transactions_on_each_page

    transactions = (
        Transaction.query.order_by(desc(Transaction.updated_at))
        .limit(limit)
        .offset(offset)
        .all()
    )

    return render_template(
        "transactions/list_transactions.html",
        transactions=transactions,
        current_page=page,
        total_pages=total_pages,
    )


@blueprint.route("/<int:id>/show", methods=("GET",))
def show_transaction(id):
    transaction = Transaction.query.get_or_404(id)
    return render_template(
        "transactions/show_transaction.html", transaction=transaction
    )


@blueprint.route("/<int:id>/return_book", methods=("POST",))
def return_book(id):
    transaction = Transaction.query.get_or_404(id)
    if transaction.is_completed:
        flash("Book has already been returned", "warning")
        return redirect(url_for("transactions.show_transaction", id=id)), 400

    transaction.return_book_and_pay_dues()
    flash("Book has been returned successfully", "success")
    return redirect(url_for("transactions.show_transaction", id=id))

foss_library/templates/books/list_books.html
{% extends "layout.html" %}
{% block content %}
<div class="container d-flex my-2">
  <h1 class="fs-2 me-auto">Available books</h1>

  <span class="fs-2 mx-1">
    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
      </svg>
    </button>
    <div class="dropdown-menu w-25">
      <form class="px-4 py-3">
        <div class="form-group">
          {{ search_form.title.label }}
          {{ search_form.title(class="form-control", autocomplete="off") }}
        </div>
        <div class="form-group">
          {{ search_form.author.label }}
          {{ search_form.author(class="form-control", autocomplete="off") }}
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
      </form>
    </div>
  </span>
  <a class="fs-2 mx-1" href="{{ url_for("books.create_book") }}">
    <button class="btn btn-primary">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
        <path d="M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z"/>
      </svg>
    </button>
  </a>
</div>

<hr />

<div class="container">
  <table class="table">
    <thead>
      <th class="align-middle text-center" scope="col">Book ID</th>
      <th class="align-middle text-center" scope="col">Title</th>
      <th class="align-middle text-center" scope="col">ISBN 13</th>
      <th class="align-middle text-center" scope="col">Authors</th>
      <th class="align-middle text-center" scope="col">Unreturned stock</th>
      <th class="align-middle text-center" scope="col">Available stock</th>
      <th class="align-middle text-center" scope="col">Total stock</th>
      <th class="align-middle text-center" scope="col">Rent per day</th>
      <th class="align-middle text-center" scope="col">Update</th>
      <th class="align-middle text-center" scope="col">Delete</th>
    </thead>

    <tbody>
      {% for book in books %}
      <tr>
        <th class="align-middle text-center" scope="row">{{ book.id }}</th>
        <td class="align-middle text-center"><a class="text-reset" href="{{ url_for("books.show_book", id=book.id) }}">{{ book.title }}</a></td>
        <td class="align-middle text-center">{{ book.isbn13 }}</td>
        <td class="align-middle text-center">
          {% for author in book.authors.split("/") %}
          <a href="{{ url_for("books.list_books", author=author) }}" class="text-reset">{{ author }}</a>{% if loop.nextitem %}, {% endif %}
          {% endfor %}
        </td>
        <td class="align-middle text-center">{{ book.unreturned_stock }}</td>
        <td class="align-middle text-center">{{ book.available_stock }}</td>
        <td class="align-middle text-center">{{ book.total_stock }}</td>
        <td class="align-middle text-center">₹{{ book.rent_per_day }}</td>
        <td class="align-middle text-center">
          <a class="d-flex justify-content-center align-items-center text-decoration-none" href="{{ url_for("books.update_book", id=book.id) }}">
            <button class="btn btn-link text-reset text-decoration-none d-inline-flex justify-content-center align-items-center px-0">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
              </svg>
            </button>
          </a>
        </td>
        <td class="align-middle text-center">
          <form class="d-flex justify-content-center align-items-center text-danger" action="{{ url_for("books.delete_book", id=book.id) }}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <button
              type="submit"
              class="btn btn-link text-reset text-decoration-none d-inline-flex justify-content-center align-items-center px-0"
              onclick="return confirm('Are you sure you want to delete this book?');"
            >
                <svg class="icon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                </svg>
            </button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<nav aria-label="Page navigation" class="d-flex justify-content-center">
  <ul class="pagination pagination-md">
    {% if current_page > 1 %}
      <li class="page-item"><a class="page-link" href="{{ url_for("books.list_books", page=current_page-1) }}">Previous</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
    {% endif %}

    {% for page_number in range(1, total_pages+1) %}
      {% if page_number == current_page %}
      <li class="page-item active"><a class="page-link selected" href="{{ url_for("books.list_books", page=page_number) }}">{{ page_number }}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="{{ url_for("books.list_books", page=page_number) }}">{{ page_number }}</a></li>
      {% endif %}
    {% endfor %}

    {% if current_page < total_pages %}
      <li class="page-item"><a class="page-link" href="{{ url_for("books.list_books", page=current_page+1) }}">Next</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
    {% endif %}
  </ul>
</nav>
{% endblock %}

foss_library/templates/books/show_book.html
{% extends "layout.html" %}
{% block content %}
<div class="container d-flex my-2">
  <h1 class="fs-2 me-auto">Book details</h1>

  <span class="fs-2 mx-1">
    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
      </svg>
    </button>
    <div class="dropdown-menu w-25">
      <form class="px-4 py-3" action="{{ url_for("books.list_books") }}">
        <div class="form-group">
          {{ search_form.title.label }}
          {{ search_form.title(class="form-control", autocomplete="off") }}
        </div>
        <div class="form-group">
          {{ search_form.author.label }}
          {{ search_form.author(class="form-control", autocomplete="off") }}
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
      </form>
    </div>
  </span>
  <a class="fs-2 mx-1" href="{{ url_for("books.create_book") }}">
    <button class="btn btn-primary">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
        <path d="M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z"/>
      </svg>
    </button>
  </a>
</div>

<hr />

<div class="container">
  <div class="row row-g-2">
    <div class="col col-9">
      <h1 class="fs-3">{{ book.title }}</h1>
    </div>
    <div class="col col-3 d-flex justify-content-end">
      <div class="dropdown show px-1">
        <a class="btn btn-secondary dropdown-toggle" href="#start-return" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Take return
        </a>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">

          <form class="px-4 py-1" action="{{ url_for("books.initiate_book_return", id=book.id) }}" method="POST">

            {{ return_form.csrf_token }}

            <div class="form-group row row-g-2">
              {{ return_form.member_id.label("Member ID") }}
              <span class="col col-12">
                {{ return_form.member_id(class="form-control", placeholder="123") }}
              </span>

            </div>

            <div class="form-group row row-g-2">
              <span class="col col-6">
                <button class="btn btn-primary" type="submit">Go</button>
              </span>
            </div>
          </form>
        </div>
      </div>

      <div class="dropdown show px-1">
        <a class="btn btn-secondary dropdown-toggle" href="#issue-book" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Issue to
        </a>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">

          <form class="px-4 py-1" action="{{ url_for("books.issue_book", id=book.id) }}" method="POST">

            {{ issue_form.csrf_token }}

            <div class="form-group row row-g-2">
              {{ issue_form.member_id.label }}
              <span class="col col-12">
                {{ issue_form.member_id(class="form-control") }}
              </span>

            </div>

            <div class="form-group row row-g-2">
              <span class="col col-6">
                <button class="btn btn-primary" type="submit">
                  Issue
                </button>
              </span>
            </div>
          </form>
        </div>
      </div>
    </div>

    <div class="col col-1">
      <span class="fw-bold">Authors: </span>
    </div>
    <div class="col col-8">
      <span class="fw-light">{{ book.authors|replace('/', ', ') }}</span>
    </div>
    <div class="col col-3"></div>
  </div>
</div>

<div class="container mt-2">
  <div class="row row-g-2">

    <div class="container py-2 col col-6">

      <div class="row py-2 bg-light">
        <div class="col col-6">
          <span class="fw-bold">ISBN </span>
        </div>
        <div class="col col-6">
          <span class="font-monospace">{{ book.isbn }}</span>
        </div>
      </div>

      <div class="row py-2">
        <div class="col col-6">
          <span class="fw-bold">ISBN 13 </span>
        </div>
        <div class="col col-6">
          <span class="font-monospace">{{ book.isbn13 }}</span>
        </div>
      </div>

      <div class="row py-2 bg-light">
        <div class="col col-6">
          <span class="fw-bold">Number of Pages </span>
        </div>
        <div class="col col-6">
          <span class="font-monospace">{{ book.num_pages }}</span>
        </div>
      </div>

      <div class="row py-2">
        <div class="col col-6">
          <span class="fw-bold">Language Code </span>
        </div>
        <div class="col col-6">
          <span class="font-monospace">{{ book.language_code }}</span>
        </div>
      </div>
 
      <div class="row py-2 bg-light">
        <div class="col col-6">
          <span class="fw-bold">Publisher </span>
        </div>
        <div class="col col-6">
          <span class="font-monospace">{{ book.publisher_name }}</span>
        </div>
      </div>

      <div class="row py-2">
        <div class="col col-6">
          <span class="fw-bold">Publication Date </span>
        </div>
        <div class="col col-6">
          <span class="font-monospace">{{ book.publication_date.strftime("%d %B, %Y") }}</span>
        </div>
      </div>
    </div>

    <div class="container py-2 col col-6">

      <div class="row py-2">
        <div class="col col-6">
          <span class="fw-bold">Available stock </span>
        </div>
        <div class="col col-6">
          <span class="font-monospace">{{ book.available_stock }}</span>
        </div>
      </div>

      <div class="row py-2 bg-light">
        <div class="col col-6">
          <span class="fw-bold">Total stock </span>
        </div>
        <div class="col col-6">
          <span class="font-monospace">{{ book.total_stock }}</span>
        </div>
      </div>

      <div class="row py-2">
        <div class="col col-6">
          <span class="fw-bold">Unreturned stock </span>
        </div>
        <div class="col col-6">
          <span class="font-monospace">{{ book.unreturned_stock }}</span>
        </div>
      </div>

      <div class="row py-2 bg-light">
        <div class="col col-6">
          <span class="fw-bold">Average rating </span>
        </div>
        <div class="col col-6">
          <span class="font-monospace">{{ book.average_rating }}</span>
        </div>
      </div>

      <div class="row py-2">
        <div class="col col-6">
          <span class="fw-bold">Ratings count </span>
        </div>
        <div class="col col-6">
          <span class="font-monospace">{{ book.ratings_count }}</span>
        </div>
      </div>

      <div class="row py-2 bg-light">
        <div class="col col-6">
          <span class="fw-bold">Text reviews count</span>
        </div>
        <div class="col col-6">
          <span class="font-monospace">{{ book.text_reviews_count }}</span>
        </div>
      </div>

    </div>
  </div>
</div>

<div class="container mt-2">

  <h1 class="fs-3">Borrowers</h1>

  <table class="table">

    <thead>
      <th scope="col">Transaction ID</th>
      <th scope="col">Borrowed by</th>
      <th scope="col">Borrowed at</th>
      <th scope="col">Dues</th>
      <th scope="col">Accept return</th>
    </thead>

    <tbody>
      {# TODO: Add pagination #}
      {% for transaction in book.transactions %}
      {% if not transaction.is_completed %}

      <tr>
        <th scope="col">
          <a class="text-reset" href="{{ url_for("transactions.show_transaction", id=transaction.id) }}">
            {{ transaction.id }}
          </a>
        </th>

        <td>
          {# <a class="text-reset" href="{{ url_for("members.show_member", id=transaction.member.id) }}"> #}
            {{ transaction.member.name }}
          {# </a> #}
        </td>

        <td>
          {{ transaction.borrowed_at }}
        </td>

        <td>
          ₹{{ transaction.dues }}
        </td>

        <td>

          <form
            class="form"
            action="{{ url_for("transactions.return_book", id=transaction.id) }}"
            method="POST"
          >
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <button
              class="btn btn-primary"
              type="submit"
              onclick="return confirm('Can you confirm that you have received a payment of {{ transaction.dues }} and the book to return?');"
            >
              Accept return
            </button>
          </form>

        </td>
      </tr>

      {% endif %}
      {% endfor %}
    </tbody>

  </table>

</div>
{% endblock %}